export const SPECIALIZATIONS = [
    "Cardiology",
    "Dermatology",
    "Endocrinology",
    "Family Medicine",
    "Gastroenterology",
    "Hematology",
    "Internal Medicine",
    "Nephrology",
    "Neurology",
    "Obstetrics & Gynecology",
    "Oncology",
    "Ophthalmology",
    "Orthopedics",
    "Otolaryngology (ENT)",
    "Pediatrics",
    "Plastic Surgery",
    "Psychiatry",
    "Pulmonology",
    "Radiology",
    "Rheumatology",
    "Sports Medicine",
    "Urology",
    "Vascular Surgery",
    "General Surgery",
    "Emergency Medicine",
    "Anesthesiology",
    "Pathology",
    "Physical Medicine",
    "Nuclear Medicine",
    "Dental Surgery"
  ] as const;
  
  export const EXPERTISE_AREAS = [
    "Cardiac Surgery",
    "Diabetes Management",
    "Skin Disorders",
    "Hormone Disorders",
    "Digestive Diseases",
    "Blood Disorders",
    "Kidney Diseases",
    "Brain & Nerve Disorders",
    "High-Risk Pregnancy",
    "Cancer Treatment",
    "Eye Surgery",
    "Joint Replacement",
    "Ear Surgery",
    "Pediatric Care",
    "Cosmetic Surgery",
    "Mental Health",
    "Lung Diseases",
    "Diagnostic Imaging",
    "Arthritis Treatment",
    "Sports Injuries",
    "Urological Surgery",
    "Vascular Diseases",
    "Emergency Care",
    "Pain Management",
    "Preventive Medicine",
    "Women's Health",
    "Men's Health",
    "Geriatric Care",
    "Nutrition & Diet",
    "Rehabilitation"
  ] as const;