export const SPECIALIZATIONS = [
    "Cardiology",
    "Dermatology",
    "Endocrinology",
    "Family Medicine",
    "Gastroenterology",
    "Hematology",
    "Internal Medicine",
    "Nephrology",
    "Neurology",
    "Obstetrics & Gynecology",
    "Oncology",
    "Ophthalmology",
    "Orthopedics",
    "Otolaryngology (ENT)",
    "Pediatrics",
    "Plastic Surgery",
    "Psychiatry",
    "Pulmonology",
    "Radiology",
    "Rheumatology",
    "Sports Medicine",
    "Urology",
    "Vascular Surgery",
    "General Surgery",
    "Emergency Medicine",
    "Anesthesiology",
    "Pathology",
    "Physical Medicine",
    "Nuclear Medicine",
    "Dental Surgery"
  ] as const;
  
  export const EXPERTISE_AREAS = [
    "Piles", 
    "High-Blood-Pressure",
    "Diarrhea",
    "Cardiac",
    "Diabetes",
    "Acne",
    "Migraine",
    "Depression",
    "Skins-Disorders",
    "Hormone",
    "Digestive",
    "Blood-Disorders",
    "Kidney",
    "Brain-Nerve-Disorders",
    "Pregnancy",
    "Cancer",
    "Eye",
    "Joint-Pain",
    "Ear",
    "Pediatric-Care",
    "Cosmetic",
    "Mental-Health",
    "Lungs",
    "Diagnostic-Imaging",
    "Arthritis",
    "Sports-Injuries",
    "Urological-Surgery",
    "Vascular-Diseases",
    "Emergency-Care",
    "Pain-Management",
    "Preventive-Medicine",
    "Womens-Health",
    "Mens-Health",
    "Geriatric-Care",
    "Nutrition-Diet",
    "Rehabilitation",
    "StomachPain"
  ] as const;