export const NURSING_SERVICES = [
  "Body Vitals (with sugar check)",
  "Body Vitals Check (B.P, temp)",
  "Wound Dressing",
  "IV Injections, Medications",
  "Stitches Removal",
  "Infusion Therapy",
  "Nasogastric Feeding Tube",
  "Catheterization",
  "Tracheostomy Care",
  "Colostomy/Ostomy Care",
  "Diabetic Care",
  "Bedsore/Pressure Ulcer Management",
  "Post-Surgical Care",
  "Elderly Care",
  "Nebulization Therapy",
  "Oxygen Administration",
  "Blood Sample Collection",
  "ECG Monitoring",
  "Urinary Catheter Care",
  "Enteral Nutrition Management",
  "Pain Management",
  "Physical Therapy Assistance",
  "Respiratory Therapy",
  "Palliative Care",
  "Medication Administration",
  "Home Health Assessment",
  "Rehabilitation Support",
  "Maternal-Newborn Care"
]; 